./filo2 ../instances/I/Abruzzo.vrp --optimization-seconds 2613 > Abruzzo.txt
./filo2 ../instances/I/Basilicata.vrp --optimization-seconds 2722 > Basilicata.txt
./filo2 ../instances/I/Calabria.vrp --optimization-seconds 2299 > Calabria.txt
./filo2 ../instances/I/Campania.vrp --optimization-seconds 4417 > Campania.txt
./filo2 ../instances/I/Emilia-Romagna.vrp --optimization-seconds 3263 > Emilia-Romagna.txt
./filo2 ../instances/I/Friuli-Venezia-Giulia.vrp --optimization-seconds 416 > Friuli-Venezia-Giulia.txt
./filo2 ../instances/I/Lazio.vrp --optimization-seconds 3938 > Lazio.txt
./filo2 ../instances/I/Liguria.vrp --optimization-seconds 2964 > Liguria.txt
./filo2 ../instances/I/Lombardia.vrp --optimization-seconds 7990 > Lombardia.txt
./filo2 ../instances/I/Marche.vrp --optimization-seconds 3634 > Marche.txt
./filo2 ../instances/I/Molise.vrp --optimization-seconds 1901 > Molise.txt
./filo2 ../instances/I/Piemonte.vrp --optimization-seconds 2721 > Piemonte.txt
./filo2 ../instances/I/Puglia.vrp --optimization-seconds 2957 > Puglia.txt
./filo2 ../instances/I/Sardegna.vrp --optimization-seconds 2690 > Sardegna.txt
./filo2 ../instances/I/Sicilia.vrp --optimization-seconds 3298 > Sicilia.txt
./filo2 ../instances/I/Toscana.vrp --optimization-seconds 5793 > Toscana.txt
./filo2 ../instances/I/Trentino-Alto-Adige.vrp --optimization-seconds 2292 > Trentino-Alto-Adige.txt
./filo2 ../instances/I/Umbria.vrp --optimization-seconds 2124 > Umbria.txt
./filo2 ../instances/I/Valle-D-Aosta.vrp --optimization-seconds 2620 > Valle-D-Aosta.txt
./filo2 ../instances/I/Veneto.vrp --optimization-seconds 5131 > Veneto.txt
